-- MySQL Script generated by MySQL Workbench
-- Tue Jan 19 15:22:25 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @old_unique_checks=@@unique_checks,
                         unique_checks=0;


SET @old_foreign_key_checks=@@foreign_key_checks,
                              foreign_key_checks=0;


SET @old_sql_mode=@@sql_mode,
                    sql_mode='TRADITIONAL,ALLOW_INVALID_DATES';


SET @old_character_set_client=@@character_set_client ;


SET @old_character_set_results=@@character_set_results ;


SET @old_collation_connection=@@collation_connection ;


SET NAMES utf8 ;


SET @old_time_zone=@@time_zone ;


SET time_zone='+00:00' ;


SET @old_unique_checks=@@unique_checks,
                         unique_checks=0 ;


SET @old_foreign_key_checks=@@foreign_key_checks,
                              foreign_key_checks=0 ;


SET @old_sql_mode=@@sql_mode,
                    sql_mode='NO_AUTO_VALUE_ON_ZERO' ;


SET @old_sql_notes=@@sql_notes,
                     sql_notes=0 ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
 -- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER
SET utf8 ;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`customer` ( `id` INT NOT NULL auto_increment, `name` varchar(45) NOT NULL, `email_address` varchar(45) NOT NULL, `squad` varchar(45) NOT NULL, `name_on_back` varchar(45) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `id_unique` (`id` ASC)) engine = innodb;

-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`order` ( `id` INT NOT NULL auto_increment, `order1` varchar(45) NOT NULL, `order1size` varchar(45) NOT NULL, `order1number` varchar(45) NOT NULL, `order2` varchar(45) NOT NULL, `order2size` varchar(45) NOT NULL, `order2number` varchar(45) NOT NULL, `order3` varchar(45) NOT NULL, `order3size` varchar(45) NOT NULL, `order3number` varchar(45) NOT NULL, PRIMARY KEY (`id`)) engine = innodb;

-- -----------------------------------------------------
-- Table `mydb`.`Linking`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`linking` ( `idlinking` INT NOT NULL auto_increment, `customer_id` INT NOT NULL, `order_id` INT NOT NULL, PRIMARY KEY (`idlinking`, `customer_id`, `order_id`), INDEX `fk_linking_customer_idx` (`customer_id` ASC), INDEX `fk_linking_order1_idx` (`order_id` ASC), CONSTRAINT `fk_linking_customer`
                                             FOREIGN KEY (`customer_id`) REFERENCES `mydb`.`customer` (`id`) ON
                                             DELETE NO action ON
                                             UPDATE NO action, CONSTRAINT `fk_linking_order1`
                                             FOREIGN KEY (`order_id`) REFERENCES `mydb`.`order` (`id`) ON
                                             DELETE NO action ON
                                             UPDATE NO action) engine = innodb;

-- -----------------------------------------------------
-- Table `mydb`.`Items`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`items` ( `iditems` INT NOT NULL auto_increment, `item` varchar(45) NULL, PRIMARY KEY (`iditems`), UNIQUE INDEX `iditems_unique` (`iditems` ASC)) engine = innodb;


SET sql_mode=@old_sql_mode;


SET foreign_key_checks=@old_foreign_key_checks;


SET unique_checks=@old_unique_checks;
